---
version: 1
formatters:
  precise:
    format: '[%(asctime)s | %(levelname)s]: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: precise
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: log/epz-bot.log
    maxBytes: 1048576
    backupCount: 3
loggers:
  root:
    level: INFO
    handlers: [console, file]